language: node_js
node_js:
  - "node"
before_script:
  - pip install mkdocs
  - pip install mkdocs-material
script: 
  - yarn test
  - yarn run docs
  - mkdir public/docs/tests
  - cp tests/eslint-report.html public/docs/tests/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public/docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master