language: node_js
node_js:
  - "node"
script: 
  - yarn test
  - yarn run docs
  - mkdir public/docs/tests
  - cp tests/eslint-report.html public/docs/tests/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: apidoc
  github_token: $GITHUB_TOKEN
  on:
    branch: master