language: node_js
node_js:
  - "node"
script: 
  - yarn test
  - yarn run docs
  - mkdir apidoc/tests
  - cp tests/eslint-report.html apidoc/tests/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: apidoc
  github_token: $GITHUB_TOKEN
  on:
    branch: master