site_name: MCPR Docs
site_description: MCPR - The ultimate Minecraft plugin registry documentation!
theme: material
copyright: Copyright &copy; 2017 Filiosoft, LLC
site_author: Filiosoft, LLC
repo_url: https://github.com/mcpr/mcpr/
site_dir: docs-site
pages:
    - About The Project:
      - About MCPR: index.md
      - Why MCPR: about/why.md
      - Software Comparison: about/comparison.md
      - GPG Signature: about/gpg.md
      - Roadmap: about/roadmap.md
    - API: 
      - MCPR API: api/index.md
      - Endpoints: api/endpoints.md
markdown_extensions:
    - admonition:
    - footnotes:
extra_css:
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css