version: '2.1'
services:
  caddy:
    restart: always
    image: abiosoft/caddy:latest
    depends_on:
    - app
    ports:
    - 80:80
    - 443:443
    command: --conf /etc/Caddyfile -quic --log stdout
    env_file:
     - .env
    volumes:
    - ./.caddy/certs:/root/.caddy
    - ./.caddy/logs:/var/log/caddy:Z
    - ./Caddyfile:/etc/Caddyfile
  app:
    restart: always
    image: mcpr/mcpr:latest    
    ports:
     - "3000:3000"
    env_file:
     - .env